module.exports = [
    {
      name: 'Annie',
      image: 'https://placekitten.com/50/50',
      email: 'john.doe@example.com',
      phone_number: '555-555-5555',
      style: 'Modern',
      bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
     },
    {
      name: 'Isaac',
      image: 'https://placekitten.com/50/50',
      email: 'jane.smith@example.com',
      phone_number: '555-555-5555',
      style: 'Modern',
      bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      name: 'Lorraine',
      image: '',
      email: 'bob.johnson@example.com',
      phone_number: '555-555-5555',
      style: 'Modern',
      bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      name: 'Mal',
      image: 'https://placekitten.com/50/50',
      email: 'jane.smith@example.com',
      phone_number: '555-555-5555',
      style: 'Modern',
      bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    {
      name: 'Zane',
      image: 'https://placekitten.com/50/50',
      email: 'bob.johnson@example.com',
      phone_number: '555-555-5555',
      style: 'Modern',
      bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
  ]