module.exports = [ {
    title: 'Annie01',
    pic: 'https://drive.google.com/file/d/1thdydC3cLVpyiXgAm5Djm4bKwpJo47Cm/view?usp=sharing',
    artist: '64420b0b403305b28b482d7a',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 20,
    year: '2020',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Annie02',
    pic: 'https://drive.google.com/file/d/14eMvjepIJjprz0hj7eiceQLJ0y6Q_s3z/view?usp=sharing',
    artist: '64420b0b403305b28b482d7a',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 20,
    year: '2020',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Annie03',
    pic: 'https://drive.google.com/file/d/15Rjn64rjE99w43gengTYZGRZZpz7S-Uy/view?usp=sharing',
    artist: '64420b0b403305b28b482d7a',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Isaac01',
    pic: 'https://drive.google.com/file/d/1_CGj8mv9pZwnQj02-lwX5h5jyX82HPst/view?usp=sharing',
    artist: '64420b0b403305b28b482d7b',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 30,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Isaac02',
    pic: 'https://drive.google.com/file/d/1V08RhztxA0rxevEsUDItJ-DcO2Gq8UPN/view?usp=sharing',
    artist: '64420b0b403305b28b482d7b',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Isaac03',
    pic: 'https://drive.google.com/file/d/1SXhh81zTq8IIva0rHeosi4Zwt0Xn_msg/view?usp=sharing',
    artist: '64420b0b403305b28b482d7b',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 45,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Lorraline01',
    pic: 'https://drive.google.com/file/d/1F9Px69jVvIsZwzJVfofQvCQZOJ4cKXsP/view?usp=sharing',
    artist: '64420b0b403305b28b482d7c',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Lorraline02',
    pic: 'https://drive.google.com/file/d/1yMIUghyzLNECl4laaam4jeTckiIfbiQW/view?usp=sharing',
    artist: '64420b0b403305b28b482d7c',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Lorraline03',
    pic: 'https://drive.google.com/file/d/1q8wgj_ecomt9pnnn8vXf0Lr8-myKCV6E/view?usp=sharing',
    artist: '64420b0b403305b28b482d7c',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Mal01',
    pic: 'https://drive.google.com/file/d/1z1OVhmwjl00faZyy6ulX3ZN6sfckeXSr/view?usp=sharing',
    artist: '64420b0b403305b28b482d7d',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Mal02',
    pic: 'https://drive.google.com/file/d/1d5Q70qZG1G4-F9FtO1V_Ek3q0qsxMmAX/view?usp=sharing',
    artist: '64420b0b403305b28b482d7d',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Mal03',
    pic: 'https://drive.google.com/file/d/1aZtNnkMydoS2kGTAgNf2oVwE6jJ9v1Os/view?usp=sharing',
    artist: '64420b0b403305b28b482d7d',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Zane01',
    pic: 'https://drive.google.com/file/d/1uhZ43sCNTUUNpzfK4Vk9-ZgHRSU1JjA_/view?usp=sharing',
    artist: '64420b0b403305b28b482d7e',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Zane02',
    pic: 'https://drive.google.com/file/d/1MHwZDuJZogI_9-qzvASATesMksMKG-05/view?usp=sharing',
    artist: '64420b0b403305b28b482d7e',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},{
    title: 'Zane03',
    pic: 'https://drive.google.com/file/d/1-mV4vgvgviCiMGbxtBMpzElxOQJYlFUZ/view?usp=sharing',
    artist: '64420b0b403305b28b482d7e',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price: 40,
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: false,
    copies: 1,
},
]