module.exports = [ {
    id: '',
    title: 'Annie01',
    pic: './public/imgs/pexels-alena-koval-886521.jpg',
    artist: 'Annie',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$20',
    year: '2020',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Annie02',
    pic: './public/imgs/pexels-anni-roenkae-2156881.jpg',
    artist: 'Annie',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$20',
    year: '2020',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Annie03',
    pic: './public/imgs/pexels-matheus-viana-3354675.jpg',
    artist: 'Annie',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Isaac01',
    pic: './public/imgs/pexels-brakou-abdelghani-1723637.jpg',
    artist: 'Isaac',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$30',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Isaac02',
    pic: './public/imgs/pexels-cliford-mervil-2469122.jpg',
    artist: 'Isaac',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Isaac03',
    pic: './public/imgs/pexels-dids-4951280.jpg',
    artist: 'Isaac',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$45',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Lorraline01',
    pic: './public/imgs/pexels-eberhard-grossgasteiger-2086361.jpg',
    artist: 'Lorraline',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Lorraline02',
    pic: './public/imgs/pexels-eberhard-grossgasteiger-2088170.jpg',
    artist: 'Lorraline',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Lorraline03',
    pic: './public/imgs/pexels-eberhard-grossgasteiger-2088203.jpg',
    artist: 'Lorraline',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Mal01',
    pic: './public/imgs/pexels-egil-sjøholt-1906658.jpg',
    artist: 'Mal',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Mal02',
    pic: './public/imgs/pexels-evie-shaffer-2395249.jpg',
    artist: 'Mal',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Mal03',
    pic: './public/imgs/pexels-fathi-vee-1020478.jpg',
    artist: 'Mal',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Zane01',
    pic: './public/imgs/pexels-ian-beckley-2440079.jpg',
    artist: 'Zane',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Zane02',
    pic: './public/imgs/pexels-javon-swaby-1697912.jpg',
    artist: 'Zane',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},{
    id: '',
    title: 'Zane03',
    pic: './public/imgs/pexels-joão-cabral-3299386.jpg',
    artist: 'Zane',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:'$40',
    year: '2021',
    style: 'modern',
    size: '10X10',
    sold: 'false',
    copies:'1',
},

]